version: '3.8'
services:
  jobmanager:
    image: flink:2.0.0-scala_2.12-java21
    ports:
      - "8081:8081" # Flink Web UI
    command: jobmanager
    networks:
      - flink-study-ntw
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
    # --- AJUSTE: Montando volumes ---
    volumes:
      - ./pyflink_jobs:/opt/flink/pyflink_jobs
      - ./flink_connectors/flink-connector-kafka-4.0.1-2.0.jar:/opt/flink/lib/flink-connector-kafka-4.0.1-2.0.jar

  taskmanager:
    image: flink:2.0.0-scala_2.12-java21
    depends_on:
      - jobmanager
    command: taskmanager
    networks:
      - flink-study-ntw
    scale: 2 # Exemplo: escalando para 2 TaskManagers
    environment:
      - |
        FLINK_PROPERTIES=
        jobmanager.rpc.address: jobmanager
        taskmanager.numberOfTaskSlots: 2

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.3
    container_name: zookeeper
    networks:
      - flink-study-ntw
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-kafka:7.5.3
    container_name: kafka
    networks:
      - flink-study-ntw
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9094:9094" # Acesso externo da sua máquina
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://localhost:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    networks: # <-- Ajuste 1: Conectado na mesma rede do Kafka
      - flink-study-ntw
    environment:
      # Ajuste 2: Apontando para o endereço INTERNO do Kafka
      KAFKA_BROKERCONNECT: "kafka:9092" 
    depends_on:
      - kafka

networks:
  flink-study-ntw:
    driver: bridge